export const environment = {
  production: false,
  SUPABASE_URL: 'your-supabase-url',
  SUPABASE_KEY: 'your-supabase-anon-key',
  SUPABASE_SERVICE_ROLE_KEY: 'your-supabase-service-role-key',
  STRIPE_PUBLISHABLE_KEY: 'pk_test_your_stripe_publishable_key',
  STRIPE_WEBHOOK_SECRET: 'whsec_your_webhook_secret',
  STRIPE_PRODUCT_IDS: [],
  STRIPE_PRICE_IDS: [],
  apiUrl: 'http://localhost:3000/api',
  project_name: 'Your Project Name',
  email: 'contact@example.com',
  phone: '+1 (555) 123-4567',
  address: '123 Main St, City, State 12345',
};
